### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by rgreinho**
I added the support for Python3 to this formula, as well as the ability to install the development packages. 

I also renamed the formula as it is not Python2 only anymore.

### CODE REVIEW

**Comment by gravyboat** [comment]
@rgreinho I like the changes here, did you consider when designing this having the version of python determined via a pillar value or something like that? I'm just trying to think of this going forward and whether it's going to make things messy, or if there's a more elegant way we can make this change.

@fridiculous The ``import python2 with context`` just pulls the python2 section from the ``map.jinja`` file and says to use it.

**Comment by nmadhok** [comment]
@rgreinho Seems like good changes to me!

**Comment by rgreinho** [comment]
@gravyboat I thought of this, but I liked to see which version of Python I installed on a machine from the ``top.sls`` file. I think it is cleaner to only have a look at the ``top.sls`` file, rather than digging into the pillars. Besides in some special cases I need both Python2 and Python3 on the same machine.

**Comment by gravyboat** [comment]
@rgreinho Those are fair points, and a quick glance didn't make me consider having both on the box. Thanks for the response!

**Pull request merged**
